spring:
  datasource:
    url: jdbc:postgresql://localhost:5234/companies
    username: debuggeandoideas-qa
    password: 3R834FJEWJJH
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
